//
//  Cv3Extension.swift
//  OpencvSwift
//
//  Created by Lohann Paterno Coutinho Ferreira on 22/09/15.
//  Copyright © 2015 Lohann Paterno Coutinho Ferreira. All rights reserved.
//

import Foundation

public extension Cv3 {
    
    /**
    * ColorSpace
    */
    public class var COLOR_BGR2BGRA: CvColor { return CvColor.BGR2BGRA }
    public class var COLOR_RGB2RGBA: CvColor { return CvColor.RGB2RGBA }
    public class var COLOR_BGRA2BGR: CvColor { return CvColor.BGRA2BGR }
    public class var COLOR_RGBA2RGB: CvColor { return CvColor.RGBA2RGB }
    public class var COLOR_BGR2RGBA: CvColor { return CvColor.BGR2RGBA }
    public class var COLOR_RGB2BGRA: CvColor { return CvColor.RGB2BGRA }
    public class var COLOR_RGBA2BGR: CvColor { return CvColor.RGBA2BGR }
    public class var COLOR_BGRA2RGB: CvColor { return CvColor.BGRA2RGB }
    public class var COLOR_BGR2RGB: CvColor { return CvColor.BGR2RGB }
    public class var COLOR_RGB2BGR: CvColor { return CvColor.RGB2BGR }
    public class var COLOR_BGRA2RGBA: CvColor { return CvColor.BGRA2RGBA }
    public class var COLOR_RGBA2BGRA: CvColor { return CvColor.RGBA2BGRA }
    public class var COLOR_BGR2GRAY: CvColor { return CvColor.BGR2GRAY }
    public class var COLOR_RGB2GRAY: CvColor { return CvColor.RGB2GRAY }
    public class var COLOR_GRAY2BGR: CvColor { return CvColor.GRAY2BGR }
    public class var COLOR_GRAY2RGB: CvColor { return CvColor.GRAY2RGB }
    public class var COLOR_GRAY2BGRA: CvColor { return CvColor.GRAY2BGRA }
    public class var COLOR_GRAY2RGBA: CvColor { return CvColor.GRAY2RGBA }
    public class var COLOR_BGRA2GRAY: CvColor { return CvColor.BGRA2GRAY }
    public class var COLOR_RGBA2GRAY: CvColor { return CvColor.RGBA2GRAY }
    public class var COLOR_BGR2BGR565: CvColor { return CvColor.BGR2BGR565 }
    public class var COLOR_RGB2BGR565: CvColor { return CvColor.RGB2BGR565 }
    public class var COLOR_BGR5652BGR: CvColor { return CvColor.BGR5652BGR }
    public class var COLOR_BGR5652RGB: CvColor { return CvColor.BGR5652RGB }
    public class var COLOR_BGRA2BGR565: CvColor { return CvColor.BGRA2BGR565 }
    public class var COLOR_RGBA2BGR565: CvColor { return CvColor.RGBA2BGR565 }
    public class var COLOR_BGR5652BGRA: CvColor { return CvColor.BGR5652BGRA }
    public class var COLOR_BGR5652RGBA: CvColor { return CvColor.BGR5652RGBA }
    public class var COLOR_GRAY2BGR565: CvColor { return CvColor.GRAY2BGR565 }
    public class var COLOR_BGR5652GRAY: CvColor { return CvColor.BGR5652GRAY }
    public class var COLOR_BGR2BGR555: CvColor { return CvColor.BGR2BGR555 }
    public class var COLOR_RGB2BGR555: CvColor { return CvColor.RGB2BGR555 }
    public class var COLOR_BGR5552BGR: CvColor { return CvColor.BGR5552BGR }
    public class var COLOR_BGR5552RGB: CvColor { return CvColor.BGR5552RGB }
    public class var COLOR_BGRA2BGR555: CvColor { return CvColor.BGRA2BGR555 }
    public class var COLOR_RGBA2BGR555: CvColor { return CvColor.RGBA2BGR555 }
    public class var COLOR_BGR5552BGRA: CvColor { return CvColor.BGR5552BGRA }
    public class var COLOR_BGR5552RGBA: CvColor { return CvColor.BGR5552RGBA }
    public class var COLOR_GRAY2BGR555: CvColor { return CvColor.GRAY2BGR555 }
    public class var COLOR_BGR5552GRAY: CvColor { return CvColor.BGR5552GRAY }
    public class var COLOR_BGR2XYZ: CvColor { return CvColor.BGR2XYZ }
    public class var COLOR_RGB2XYZ: CvColor { return CvColor.RGB2XYZ }
    public class var COLOR_XYZ2BGR: CvColor { return CvColor.XYZ2BGR }
    public class var COLOR_XYZ2RGB: CvColor { return CvColor.XYZ2RGB }
    public class var COLOR_BGR2YCrCb: CvColor { return CvColor.BGR2YCrCb }
    public class var COLOR_RGB2YCrCb: CvColor { return CvColor.RGB2YCrCb }
    public class var COLOR_YCrCb2BGR: CvColor { return CvColor.YCrCb2BGR }
    public class var COLOR_YCrCb2RGB: CvColor { return CvColor.YCrCb2RGB }
    public class var COLOR_BGR2HSV: CvColor { return CvColor.BGR2HSV }
    public class var COLOR_RGB2HSV: CvColor { return CvColor.RGB2HSV }
    public class var COLOR_BGR2Lab: CvColor { return CvColor.BGR2Lab }
    public class var COLOR_RGB2Lab: CvColor { return CvColor.RGB2Lab }
    public class var COLOR_BGR2Luv: CvColor { return CvColor.BGR2Luv }
    public class var COLOR_RGB2Luv: CvColor { return CvColor.RGB2Luv }
    public class var COLOR_BGR2HLS: CvColor { return CvColor.BGR2HLS }
    public class var COLOR_RGB2HLS: CvColor { return CvColor.RGB2HLS }
    public class var COLOR_HSV2BGR: CvColor { return CvColor.HSV2BGR }
    public class var COLOR_HSV2RGB: CvColor { return CvColor.HSV2RGB }
    public class var COLOR_Lab2BGR: CvColor { return CvColor.Lab2BGR }
    public class var COLOR_Lab2RGB: CvColor { return CvColor.Lab2RGB }
    public class var COLOR_Luv2BGR: CvColor { return CvColor.Luv2BGR }
    public class var COLOR_Luv2RGB: CvColor { return CvColor.Luv2RGB }
    public class var COLOR_HLS2BGR: CvColor { return CvColor.HLS2BGR }
    public class var COLOR_HLS2RGB: CvColor { return CvColor.HLS2RGB }
    public class var COLOR_BGR2HSV_FULL: CvColor { return CvColor.BGR2HSV_FULL }
    public class var COLOR_RGB2HSV_FULL: CvColor { return CvColor.RGB2HSV_FULL }
    public class var COLOR_BGR2HLS_FULL: CvColor { return CvColor.BGR2HLS_FULL }
    public class var COLOR_RGB2HLS_FULL: CvColor { return CvColor.RGB2HLS_FULL }
    public class var COLOR_HSV2BGR_FULL: CvColor { return CvColor.HSV2BGR_FULL }
    public class var COLOR_HSV2RGB_FULL: CvColor { return CvColor.HSV2RGB_FULL }
    public class var COLOR_HLS2BGR_FULL: CvColor { return CvColor.HLS2BGR_FULL }
    public class var COLOR_HLS2RGB_FULL: CvColor { return CvColor.HLS2RGB_FULL }
    public class var COLOR_LBGR2Lab: CvColor { return CvColor.LBGR2Lab }
    public class var COLOR_LRGB2Lab: CvColor { return CvColor.LRGB2Lab }
    public class var COLOR_LBGR2Luv: CvColor { return CvColor.LBGR2Luv }
    public class var COLOR_LRGB2Luv: CvColor { return CvColor.LRGB2Luv }
    public class var COLOR_Lab2LBGR: CvColor { return CvColor.Lab2LBGR }
    public class var COLOR_Lab2LRGB: CvColor { return CvColor.Lab2LRGB }
    public class var COLOR_Luv2LBGR: CvColor { return CvColor.Luv2LBGR }
    public class var COLOR_Luv2LRGB: CvColor { return CvColor.Luv2LRGB }
    public class var COLOR_BGR2YUV: CvColor { return CvColor.BGR2YUV }
    public class var COLOR_RGB2YUV: CvColor { return CvColor.RGB2YUV }
    public class var COLOR_YUV2BGR: CvColor { return CvColor.YUV2BGR }
    public class var COLOR_YUV2RGB: CvColor { return CvColor.YUV2RGB }
    public class var COLOR_YUV2RGB_NV12: CvColor { return CvColor.YUV2RGB_NV12 }
    public class var COLOR_YUV2BGR_NV12: CvColor { return CvColor.YUV2BGR_NV12 }
    public class var COLOR_YUV2RGB_NV21: CvColor { return CvColor.YUV2RGB_NV21 }
    public class var COLOR_YUV2BGR_NV21: CvColor { return CvColor.YUV2BGR_NV21 }
    public class var COLOR_YUV420sp2RGB: CvColor { return CvColor.YUV420sp2RGB }
    public class var COLOR_YUV420sp2BGR: CvColor { return CvColor.YUV420sp2BGR }
    public class var COLOR_YUV2RGBA_NV12: CvColor { return CvColor.YUV2RGBA_NV12 }
    public class var COLOR_YUV2BGRA_NV12: CvColor { return CvColor.YUV2BGRA_NV12 }
    public class var COLOR_YUV2RGBA_NV21: CvColor { return CvColor.YUV2RGBA_NV21 }
    public class var COLOR_YUV2BGRA_NV21: CvColor { return CvColor.YUV2BGRA_NV21 }
    public class var COLOR_YUV420sp2RGBA: CvColor { return CvColor.YUV420sp2RGBA }
    public class var COLOR_YUV420sp2BGRA: CvColor { return CvColor.YUV420sp2BGRA }
    public class var COLOR_YUV2RGB_YV12: CvColor { return CvColor.YUV2RGB_YV12 }
    public class var COLOR_YUV2BGR_YV12: CvColor { return CvColor.YUV2BGR_YV12 }
    public class var COLOR_YUV2RGB_IYUV: CvColor { return CvColor.YUV2RGB_IYUV }
    public class var COLOR_YUV2BGR_IYUV: CvColor { return CvColor.YUV2BGR_IYUV }
    public class var COLOR_YUV2RGB_I420: CvColor { return CvColor.YUV2RGB_I420 }
    public class var COLOR_YUV2BGR_I420: CvColor { return CvColor.YUV2BGR_I420 }
    public class var COLOR_YUV420p2RGB: CvColor { return CvColor.YUV420p2RGB }
    public class var COLOR_YUV420p2BGR: CvColor { return CvColor.YUV420p2BGR }
    public class var COLOR_YUV2RGBA_YV12: CvColor { return CvColor.YUV2RGBA_YV12 }
    public class var COLOR_YUV2BGRA_YV12: CvColor { return CvColor.YUV2BGRA_YV12 }
    public class var COLOR_YUV2RGBA_IYUV: CvColor { return CvColor.YUV2RGBA_IYUV }
    public class var COLOR_YUV2BGRA_IYUV: CvColor { return CvColor.YUV2BGRA_IYUV }
    public class var COLOR_YUV2RGBA_I420: CvColor { return CvColor.YUV2RGBA_I420 }
    public class var COLOR_YUV2BGRA_I420: CvColor { return CvColor.YUV2BGRA_I420 }
    public class var COLOR_YUV420p2RGBA: CvColor { return CvColor.YUV420p2RGBA }
    public class var COLOR_YUV420p2BGRA: CvColor { return CvColor.YUV420p2BGRA }
    public class var COLOR_YUV2GRAY_420: CvColor { return CvColor.YUV2GRAY_420 }
    public class var COLOR_YUV2GRAY_NV21: CvColor { return CvColor.YUV2GRAY_NV21 }
    public class var COLOR_YUV2GRAY_NV12: CvColor { return CvColor.YUV2GRAY_NV12 }
    public class var COLOR_YUV2GRAY_YV12: CvColor { return CvColor.YUV2GRAY_YV12 }
    public class var COLOR_YUV2GRAY_IYUV: CvColor { return CvColor.YUV2GRAY_IYUV }
    public class var COLOR_YUV2GRAY_I420: CvColor { return CvColor.YUV2GRAY_I420 }
    public class var COLOR_YUV420sp2GRAY: CvColor { return CvColor.YUV420sp2GRAY }
    public class var COLOR_YUV420p2GRAY: CvColor { return CvColor.YUV420p2GRAY }
    public class var COLOR_YUV2RGB_UYVY: CvColor { return CvColor.YUV2RGB_UYVY }
    public class var COLOR_YUV2BGR_UYVY: CvColor { return CvColor.YUV2BGR_UYVY }
    public class var COLOR_YUV2RGB_Y422: CvColor { return CvColor.YUV2RGB_Y422 }
    public class var COLOR_YUV2BGR_Y422: CvColor { return CvColor.YUV2BGR_Y422 }
    public class var COLOR_YUV2RGB_UYNV: CvColor { return CvColor.YUV2RGB_UYNV }
    public class var COLOR_YUV2BGR_UYNV: CvColor { return CvColor.YUV2BGR_UYNV }
    public class var COLOR_YUV2RGBA_UYVY: CvColor { return CvColor.YUV2RGBA_UYVY }
    public class var COLOR_YUV2BGRA_UYVY: CvColor { return CvColor.YUV2BGRA_UYVY }
    public class var COLOR_YUV2RGBA_Y422: CvColor { return CvColor.YUV2RGBA_Y422 }
    public class var COLOR_YUV2BGRA_Y422: CvColor { return CvColor.YUV2BGRA_Y422 }
    public class var COLOR_YUV2RGBA_UYNV: CvColor { return CvColor.YUV2RGBA_UYNV }
    public class var COLOR_YUV2BGRA_UYNV: CvColor { return CvColor.YUV2BGRA_UYNV }
    public class var COLOR_YUV2RGB_YUY2: CvColor { return CvColor.YUV2RGB_YUY2 }
    public class var COLOR_YUV2BGR_YUY2: CvColor { return CvColor.YUV2BGR_YUY2 }
    public class var COLOR_YUV2RGB_YVYU: CvColor { return CvColor.YUV2RGB_YVYU }
    public class var COLOR_YUV2BGR_YVYU: CvColor { return CvColor.YUV2BGR_YVYU }
    public class var COLOR_YUV2RGB_YUYV: CvColor { return CvColor.YUV2RGB_YUYV }
    public class var COLOR_YUV2BGR_YUYV: CvColor { return CvColor.YUV2BGR_YUYV }
    public class var COLOR_YUV2RGB_YUNV: CvColor { return CvColor.YUV2RGB_YUNV }
    public class var COLOR_YUV2BGR_YUNV: CvColor { return CvColor.YUV2BGR_YUNV }
    public class var COLOR_YUV2RGBA_YUY2: CvColor { return CvColor.YUV2RGBA_YUY2 }
    public class var COLOR_YUV2BGRA_YUY2: CvColor { return CvColor.YUV2BGRA_YUY2 }
    public class var COLOR_YUV2RGBA_YVYU: CvColor { return CvColor.YUV2RGBA_YVYU }
    public class var COLOR_YUV2BGRA_YVYU: CvColor { return CvColor.YUV2BGRA_YVYU }
    public class var COLOR_YUV2RGBA_YUYV: CvColor { return CvColor.YUV2RGBA_YUYV }
    public class var COLOR_YUV2BGRA_YUYV: CvColor { return CvColor.YUV2BGRA_YUYV }
    public class var COLOR_YUV2RGBA_YUNV: CvColor { return CvColor.YUV2RGBA_YUNV }
    public class var COLOR_YUV2BGRA_YUNV: CvColor { return CvColor.YUV2BGRA_YUNV }
    public class var COLOR_YUV2GRAY_UYVY: CvColor { return CvColor.YUV2GRAY_UYVY }
    public class var COLOR_YUV2GRAY_YUY2: CvColor { return CvColor.YUV2GRAY_YUY2 }
    public class var COLOR_YUV2GRAY_Y422: CvColor { return CvColor.YUV2GRAY_Y422 }
    public class var COLOR_YUV2GRAY_UYNV: CvColor { return CvColor.YUV2GRAY_UYNV }
    public class var COLOR_YUV2GRAY_YVYU: CvColor { return CvColor.YUV2GRAY_YVYU }
    public class var COLOR_YUV2GRAY_YUYV: CvColor { return CvColor.YUV2GRAY_YUYV }
    public class var COLOR_YUV2GRAY_YUNV: CvColor { return CvColor.YUV2GRAY_YUNV }
    public class var COLOR_RGBA2mRGBA: CvColor { return CvColor.RGBA2mRGBA }
    public class var COLOR_mRGBA2RGBA: CvColor { return CvColor.mRGBA2RGBA }
    public class var COLOR_RGB2YUV_I420: CvColor { return CvColor.RGB2YUV_I420 }
    public class var COLOR_BGR2YUV_I420: CvColor { return CvColor.BGR2YUV_I420 }
    public class var COLOR_RGB2YUV_IYUV: CvColor { return CvColor.RGB2YUV_IYUV }
    public class var COLOR_BGR2YUV_IYUV: CvColor { return CvColor.BGR2YUV_IYUV }
    public class var COLOR_RGBA2YUV_I420: CvColor { return CvColor.RGBA2YUV_I420 }
    public class var COLOR_BGRA2YUV_I420: CvColor { return CvColor.BGRA2YUV_I420 }
    public class var COLOR_RGBA2YUV_IYUV: CvColor { return CvColor.RGBA2YUV_IYUV }
    public class var COLOR_BGRA2YUV_IYUV: CvColor { return CvColor.BGRA2YUV_IYUV }
    public class var COLOR_RGB2YUV_YV12: CvColor { return CvColor.RGB2YUV_YV12 }
    public class var COLOR_BGR2YUV_YV12: CvColor { return CvColor.BGR2YUV_YV12 }
    public class var COLOR_RGBA2YUV_YV12: CvColor { return CvColor.RGBA2YUV_YV12 }
    public class var COLOR_BGRA2YUV_YV12: CvColor { return CvColor.BGRA2YUV_YV12 }
    public class var COLOR_BayerBG2BGR: CvColor { return CvColor.BayerBG2BGR }
    public class var COLOR_BayerGB2BGR: CvColor { return CvColor.BayerGB2BGR }
    public class var COLOR_BayerRG2BGR: CvColor { return CvColor.BayerRG2BGR }
    public class var COLOR_BayerGR2BGR: CvColor { return CvColor.BayerGR2BGR }
    public class var COLOR_BayerBG2RGB: CvColor { return CvColor.BayerBG2RGB }
    public class var COLOR_BayerGB2RGB: CvColor { return CvColor.BayerGB2RGB }
    public class var COLOR_BayerRG2RGB: CvColor { return CvColor.BayerRG2RGB }
    public class var COLOR_BayerGR2RGB: CvColor { return CvColor.BayerGR2RGB }
    public class var COLOR_BayerBG2GRAY: CvColor { return CvColor.BayerBG2GRAY }
    public class var COLOR_BayerGB2GRAY: CvColor { return CvColor.BayerGB2GRAY }
    public class var COLOR_BayerRG2GRAY: CvColor { return CvColor.BayerRG2GRAY }
    public class var COLOR_BayerGR2GRAY: CvColor { return CvColor.BayerGR2GRAY }
    public class var COLOR_BayerBG2BGR_VNG: CvColor { return CvColor.BayerBG2BGR_VNG }
    public class var COLOR_BayerGB2BGR_VNG: CvColor { return CvColor.BayerGB2BGR_VNG }
    public class var COLOR_BayerRG2BGR_VNG: CvColor { return CvColor.BayerRG2BGR_VNG }
    public class var COLOR_BayerGR2BGR_VNG: CvColor { return CvColor.BayerGR2BGR_VNG }
    public class var COLOR_BayerBG2RGB_VNG: CvColor { return CvColor.BayerBG2RGB_VNG }
    public class var COLOR_BayerGB2RGB_VNG: CvColor { return CvColor.BayerGB2RGB_VNG }
    public class var COLOR_BayerRG2RGB_VNG: CvColor { return CvColor.BayerRG2RGB_VNG }
    public class var COLOR_BayerGR2RGB_VNG: CvColor { return CvColor.BayerGR2RGB_VNG }
    public class var COLOR_BayerBG2BGR_EA: CvColor { return CvColor.BayerBG2BGR_EA }
    public class var COLOR_BayerGB2BGR_EA: CvColor { return CvColor.BayerGB2BGR_EA }
    public class var COLOR_BayerRG2BGR_EA: CvColor { return CvColor.BayerRG2BGR_EA }
    public class var COLOR_BayerGR2BGR_EA: CvColor { return CvColor.BayerGR2BGR_EA }
    public class var COLOR_BayerBG2RGB_EA: CvColor { return CvColor.BayerBG2RGB_EA }
    public class var COLOR_BayerGB2RGB_EA: CvColor { return CvColor.BayerGB2RGB_EA }
    public class var COLOR_BayerRG2RGB_EA: CvColor { return CvColor.BayerRG2RGB_EA }
    public class var COLOR_BayerGR2RGB_EA: CvColor { return CvColor.BayerGR2RGB_EA }
    public class var COLOR_COLORCVT_MAX: CvColor { return CvColor.COLORCVT_MAX }
    
    /**
     * Types
     */
    public class var CV_8U: CvType { return CvType.UInt8() }
    public class var CV_8S: CvType { return CvType.Int8() }
    public class var CV_16U: CvType { return CvType.UInt16() }
    public class var CV_16S: CvType { return CvType.Int16() }
    public class var CV_32S: CvType { return CvType.Int32() }
    public class var CV_32F: CvType { return CvType.Float32() }
    public class var CV_64F: CvType { return CvType.Float64() }
    public class var CV_USRTYPE1: CvType { return CvType.USRTYPE1() }
    public class var CV_8UC1: CvType { return CvType.UInt8C1() }
    public class var CV_8UC2: CvType { return CvType.UInt8C2() }
    public class var CV_8UC3: CvType { return CvType.UInt8C3() }
    public class var CV_8UC4: CvType { return CvType.UInt8C4() }
    public class var CV_8SC1: CvType { return CvType.Int8C1() }
    public class var CV_8SC2: CvType { return CvType.Int8C2() }
    public class var CV_8SC3: CvType { return CvType.Int8C3() }
    public class var CV_8SC4: CvType { return CvType.Int8C4() }
    public class var CV_16UC1: CvType { return CvType.UInt16C1() }
    public class var CV_16UC2: CvType { return CvType.UInt16C2() }
    public class var CV_16UC3: CvType { return CvType.UInt16C3() }
    public class var CV_16UC4: CvType { return CvType.UInt16C4() }
    public class var CV_16SC1: CvType { return CvType.Int16C1() }
    public class var CV_16SC2: CvType { return CvType.Int16C2() }
    public class var CV_16SC3: CvType { return CvType.Int16C3() }
    public class var CV_16SC4: CvType { return CvType.Int16C4() }
    public class var CV_32SC1: CvType { return CvType.Int32C1() }
    public class var CV_32SC2: CvType { return CvType.Int32C2() }
    public class var CV_32SC3: CvType { return CvType.Int32C3() }
    public class var CV_32SC4: CvType { return CvType.Int32C4() }
    public class var CV_32FC1: CvType { return CvType.Float32C1() }
    public class var CV_32FC2: CvType { return CvType.Float32C2() }
    public class var CV_32FC3: CvType { return CvType.Float32C3() }
    public class var CV_32FC4: CvType { return CvType.Float32C4() }
    public class var CV_64FC1: CvType { return CvType.Float64C1() }
    public class var CV_64FC2: CvType { return CvType.Float64C2() }
    public class var CV_64FC3: CvType { return CvType.Float64C3() }
    public class var CV_64FC4: CvType { return CvType.Float64C4() }
    
}